name: 'Visual Regression Testing'
description: 'Automated Playwright visual regression with screenshot diffs, smart cropping, and PR comments'
author: 'Kim Eik'
branding:
  icon: 'camera'
  color: 'purple'

inputs:
  mode:
    description: 'Mode: "capture" to take screenshots, "compare" to generate diffs and comment'
    required: true

  github-token:
    description: 'GitHub token for API access (required for compare mode)'
    required: false

  playwright-command:
    description: 'Command to run Playwright tests (capture mode only)'
    required: false
    default: 'npm test'

  working-directory:
    description: 'Working directory for the action (where package.json is located)'
    required: false
    default: '.'

  screenshot-directory:
    description: 'Directory where screenshots are saved (relative to working-directory)'
    required: false
    default: 'screenshots'

  artifact-name:
    description: 'Name for screenshot artifact (capture mode only)'
    required: false
    default: 'screenshots'

  base-artifact:
    description: 'Name of base screenshots artifact (compare mode only)'
    required: false
    default: 'screenshots-base'

  pr-artifact:
    description: 'Name of PR screenshots artifact (compare mode only)'
    required: false
    default: 'screenshots-pr'

  post-comment:
    description: 'Post visual diff comment on PR (compare mode only)'
    required: false
    default: 'true'

  diff-threshold:
    description: 'Odiff threshold for pixel differences (0.0-1.0, default 0.1 = 10%)'
    required: false
    default: '0.1'

  crop-padding:
    description: 'Vertical padding around diff regions in pixels'
    required: false
    default: '50'

  crop-min-height:
    description: 'Minimum crop height in pixels'
    required: false
    default: '300'

  install-deps:
    description: 'Install npm dependencies before running tests (capture mode only)'
    required: false
    default: 'true'

  fail-on-changes:
    description: 'Fail the action if visual changes are detected (compare mode only)'
    required: false
    default: 'false'

  imgbb-api-key:
    description: 'ImgBB API key for image hosting (required for compare mode)'
    required: false
    default: ''

outputs:
  screenshot-count:
    description: 'Number of PNG files found (capture mode)'
  screenshot-directory:
    description: 'Absolute path to screenshot directory (capture mode)'
  has-diffs:
    description: 'Whether visual diffs were detected (compare mode)'
  comment-posted:
    description: 'Whether PR comment was posted (compare mode)'
  diff-images-directory:
    description: 'Absolute path to directory containing diff images (compare mode)'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/netbrain/visual-regression-action:latest'
  env:
    INPUT_MODE: ${{ inputs.mode }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_PLAYWRIGHT_COMMAND: ${{ inputs.playwright-command }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
    INPUT_SCREENSHOT_DIRECTORY: ${{ inputs.screenshot-directory }}
    INPUT_ARTIFACT_NAME: ${{ inputs.artifact-name }}
    INPUT_BASE_ARTIFACT: ${{ inputs.base-artifact }}
    INPUT_PR_ARTIFACT: ${{ inputs.pr-artifact }}
    INPUT_POST_COMMENT: ${{ inputs.post-comment }}
    INPUT_DIFF_THRESHOLD: ${{ inputs.diff-threshold }}
    INPUT_CROP_PADDING: ${{ inputs.crop-padding }}
    INPUT_CROP_MIN_HEIGHT: ${{ inputs.crop-min-height }}
    INPUT_INSTALL_DEPS: ${{ inputs.install-deps }}
    INPUT_FAIL_ON_CHANGES: ${{ inputs.fail-on-changes }}
    INPUT_IMGBB_API_KEY: ${{ inputs.imgbb-api-key }}
