name: 'Visual Regression Testing'
description: 'Automated Playwright visual regression with screenshot diffs, smart cropping, and PR comments'
author: 'Kim Eik'
branding:
  icon: 'camera'
  color: 'purple'

inputs:
  mode:
    description: 'Mode: "capture" to take screenshots, "compare" to generate diffs and comment'
    required: true

  github-token:
    description: 'GitHub token for API access (required for compare mode)'
    required: false

  playwright-command:
    description: 'Command to run Playwright tests (capture mode only)'
    required: false
    default: 'npm test'

  working-directory:
    description: 'Working directory for the action (where package.json is located)'
    required: false
    default: '.'

  screenshot-directory:
    description: 'Directory where screenshots are saved (relative to working-directory)'
    required: false
    default: 'screenshots'

  artifact-name:
    description: 'Name for screenshot artifact (capture mode only)'
    required: false
    default: 'screenshots'

  base-artifact:
    description: 'Name of base screenshots artifact (compare mode only)'
    required: false
    default: 'screenshots-base'

  pr-artifact:
    description: 'Name of PR screenshots artifact (compare mode only)'
    required: false
    default: 'screenshots-pr'

  post-comment:
    description: 'Post visual diff comment on PR (compare mode only)'
    required: false
    default: true

  diff-threshold:
    description: 'Odiff threshold for pixel differences (0.0-1.0, default 0.1 = 10%)'
    required: false
    default: '0.1'

  crop-padding:
    description: 'Vertical padding around diff regions in pixels'
    required: false
    default: '50'

  crop-min-height:
    description: 'Minimum crop height in pixels'
    required: false
    default: '300'

  install-deps:
    description: 'Install npm dependencies before running tests (capture mode only)'
    required: false
    default: true

  fail-on-changes:
    description: 'Fail the action if visual changes are detected (compare mode only)'
    required: false
    default: false

  r2-account-id:
    description: 'Cloudflare R2 Account ID (required for compare mode)'
    required: false
    default: ''

  r2-access-key-id:
    description: 'Cloudflare R2 Access Key ID (required for compare mode)'
    required: false
    default: ''

  r2-secret-access-key:
    description: 'Cloudflare R2 Secret Access Key (required for compare mode)'
    required: false
    default: ''

  r2-bucket-name:
    description: 'Cloudflare R2 bucket name (required for compare mode)'
    required: false
    default: ''

  r2-public-url:
    description: 'Cloudflare R2 public bucket URL (e.g., https://pub-xxxxx.r2.dev)'
    required: false
    default: ''

  output-format:
    description: 'Output format for diff images: "side-by-side" or "animated-gif"'
    required: false
    default: 'animated-gif'

  gif-frame-delay:
    description: 'Delay between frames in animated GIF (milliseconds). Only applies when output-format is animated-gif.'
    required: false
    default: '750'

  include-diff-in-output:
    description: 'Include the diff highlight image in output. When false, animated GIFs show only base → new.'
    required: false
    default: false

outputs:
  screenshot-count:
    description: 'Number of PNG files found (capture mode)'
  screenshot-directory:
    description: 'Absolute path to screenshot directory (capture mode)'
  has-diffs:
    description: 'Whether visual diffs were detected (compare mode)'
  comment-posted:
    description: 'Whether PR comment was posted (compare mode)'
  diff-images-directory:
    description: 'Absolute path to directory containing diff images (compare mode)'

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        # Install imagemagick, jq, curl, git (if not already present)
        if ! command -v convert &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y imagemagick git curl jq
        fi

    - name: Install odiff
      shell: bash
      run: |
        # Install odiff globally if not already installed
        if ! command -v odiff &> /dev/null; then
          npm install -g odiff-bin@4.1.1
        fi

    - name: Install action dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Install the action's own dependencies if not already installed
        if [ ! -d "node_modules" ]; then
          npm ci
        fi

    - name: Run pre-built TypeScript logic
      id: run-ts-script
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_PLAYWRIGHT-COMMAND: ${{ inputs.playwright-command }}
        INPUT_WORKING-DIRECTORY: ${{ inputs.working-directory }}
        INPUT_SCREENSHOT-DIRECTORY: ${{ inputs.screenshot-directory }}
        INPUT_ARTIFACT-NAME: ${{ inputs.artifact-name }}
        INPUT_BASE-ARTIFACT: ${{ inputs.base-artifact }}
        INPUT_PR-ARTIFACT: ${{ inputs.pr-artifact }}
        INPUT_POST-COMMENT: ${{ inputs.post-comment }}
        INPUT_DIFF-THRESHOLD: ${{ inputs.diff-threshold }}
        INPUT_CROP-PADDING: ${{ inputs.crop-padding }}
        INPUT_CROP-MIN-HEIGHT: ${{ inputs.crop-min-height }}
        INPUT_INSTALL-DEPS: ${{ inputs.install-deps }}
        INPUT_FAIL-ON-CHANGES: ${{ inputs.fail-on-changes }}
        INPUT_R2-ACCOUNT-ID: ${{ inputs.r2-account-id }}
        INPUT_R2-ACCESS-KEY-ID: ${{ inputs.r2-access-key-id }}
        INPUT_R2-SECRET-ACCESS-KEY: ${{ inputs.r2-secret-access-key }}
        INPUT_R2-BUCKET-NAME: ${{ inputs.r2-bucket-name }}
        INPUT_R2-PUBLIC-URL: ${{ inputs.r2-public-url }}
        INPUT_OUTPUT-FORMAT: ${{ inputs.output-format }}
        INPUT_GIF-FRAME-DELAY: ${{ inputs.gif-frame-delay }}
        INPUT_INCLUDE-DIFF-IN-OUTPUT: ${{ inputs.include-diff-in-output }}
